/*
 Copyright (c) 2014 Ahomé Innovation Technologies. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
package com.ait.toolkit.titanium.mobile.client.core.events;

import com.ait.toolkit.core.client.JsoHelper;
import com.ait.toolkit.core.client.JsObject;
import com.google.gwt.core.client.JavaScriptObject;

/**
 * Class used in any event or callback which needs to report a success or
 * failure.
 * 
 */
public class ErrorResponse extends JsObject {

    protected ErrorResponse(JavaScriptObject obj) {
        jsObj = obj;
    }

    /**
     * Error code. Returns 0 if success is true.
     * <p>
     * Error code will be 0 if success is true, nonzero otherwise. If the error
     * was generated by the operating system, that system's error value is used.
     * Otherwise, this value will be -1.
     */
    public int getCode() {
        return JsoHelper.getAttributeAsInt(jsObj, "code");
    }

    /**
     * Error message, if any returned.
     * <p>
     * Will be undefined if success is true.
     */
    public String getError() {
        return JsoHelper.getAttribute(jsObj, "error");
    }

    /**
     * Indicates if the operation succeeded.
     * <p>
     * Returns true if request succeeded, false otherwise.
     */
    public boolean isSuccess() {
        return JsoHelper.getAttributeAsBoolean(jsObj, "success");
    }
}
