/*
 Copyright (c) 2014 Ahomé Innovation Technologies. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
package com.ait.toolkit.titanium.mobile.modules.facebook.client;

import com.ait.toolkit.titanium.mobile.client.core.events.Event;
import com.google.gwt.core.client.JavaScriptObject;

public class FBLoginEvent extends Event {

    protected FBLoginEvent(JavaScriptObject obj) {
        jsObj = obj;
    }

    /**
     * Indicates if the user canceled the login request by closing the dialog.
     */
    public native boolean isCanceled() /*-{
		var jso = this.@com.ait.toolkit.core.client.JsObject::getJsObj()();
		return jso.canceled;
    }-*/;

    /**
     * Error code. Error code will be 0 if success is true, nonzero otherwise.
     * If the error was generated by the operating system, that system's error
     * value is used. Otherwise, this value will be -1
     */
    public native int getCode() /*-{
		var jso = this.@com.ait.toolkit.core.client.JsObject::getJsObj()();
		return jso.code;
    }-*/;

    /**
     * Data returned by Facebook when we query for the UID (using graph path
     * "me") after a successful login. Data is in JSON format, and includes
     * information such as user name, locale and gender.
     */
    public native FBData getData() /*-{
		var jso = this.@com.ait.toolkit.core.client.JsObject::getJsObj()();
		var obj = jso.data;
		return @com.ait.toolkit.titanium.mobile.modules.facebook.client.FBData::new(Lcom/google/gwt/core/client/JavaScriptObject;)(obj);
    }-*/;

    /**
     * Error message, if any returned. Will be undefined if success is true.
     */
    public native String getError() /*-{
		var jso = this.@com.ait.toolkit.core.client.JsObject::getJsObj()();
		return jso.error;
    }-*/;

    /**
     * Indicates if the user was logged in successfully. Returns true if request
     * succeeded, false otherwise.
     */
    public native boolean isSuccess() /*-{
		var jso = this.@com.ait.toolkit.core.client.JsObject::getJsObj()();
		return jso.success;
    }-*/;

    /**
     * User ID returned by Facebook if the login was successful.
     */
    public native String getUid() /*-{
		var jso = this.@com.ait.toolkit.core.client.JsObject::getJsObj()();
		return jso.uid;
    }-*/;
}
